# Writes StarBuildStamp.cpp with the current build time, baked in at compile
# time rather than read from a file's mtime at runtime (works identically
# regardless of how the binary later gets copied/packaged). Run via a custom
# target with no declared inputs (see core/CMakeLists.txt), so - unlike
# StarVersion.cpp.in's CONFIGURE_FILE, which only reruns when CMake itself
# reconfigures - this reruns on every single build invocation, not just
# every commit or every CMakeLists.txt change. That matters for local
# dev-loop iteration: the git commit (StarSourceIdentifierString) doesn't
# change between uncommitted edits, so it can't answer "did my last change
# actually get rebuilt?" - this can.
#
# Usage: cmake -DOUT=<path> -P GenerateBuildStamp.cmake
string(TIMESTAMP STAR_BUILD_UNIX_TIME "%s" UTC)
string(SHA1 STAR_BUILD_STAMP_HASH "${STAR_BUILD_UNIX_TIME}")
string(SUBSTRING "${STAR_BUILD_STAMP_HASH}" 0 12 STAR_BUILD_STAMP_SHORT)
string(TIMESTAMP STAR_BUILD_DATE "%d/%m/%Y %H:%M:%S" UTC)

file(WRITE "${OUT}" "// Generated by GenerateBuildStamp.cmake on every build - do not edit.
// The include matters: a const global with no prior extern declaration
// visible gets internal linkage by default in C++, invisible to every
// other translation unit despite compiling fine on its own - this must see
// StarVersion.hpp's extern declarations first to actually export these.
#include \"StarVersion.hpp\"
namespace Star {
char const* const StarBuildStampString = \"${STAR_BUILD_STAMP_SHORT}\";
char const* const StarBuildUnixTimeString = \"${STAR_BUILD_UNIX_TIME}\";
char const* const StarBuildDateString = \"${STAR_BUILD_DATE} UTC\";
}
")
